{% set version = "2.0.0" %}
{% set sha256 = "2566f99591d615037fce65a815ac31a3eccad6c23d6d5f404f9eb8e1513fc901" %}

package:
  name: links
  version: {{ version }}

source:

  url: https://github.com/bcgsc/LINKS/releases/download/v2.0.0/links_v2-0-0.tar.gz
  sha256: {{ sha256 }}
  patches:
    - links.patch
    - links-osx.patch # [osx]

build:
  number: 0 

requirements:
  build:
    - swig
    - {{ compiler('cxx') }}
  host:
    - perl >=5.32.1
  run:
    - perl >=5.32.1
test:
  commands:
    - LINKS | grep 'Usage' > /dev/null

about:
  summary: Long Interval Nucleotide K-mer Scaffolder
  home: https://github.com/bcgsc/LINKS
  license: GPLv3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'

