{% set version = "1.5.2" %}

package:
  name: pygtftk
  version: '{{ version }}'

source:
  url: 'https://github.com/dputhier/pygtftk/archive/v{{ version }}.tar.gz'
  sha256: 0484ba288405581f0dbb2daa1edce463c66385d254a6859e5bdb23a97bbf9860

build:
  number: 0
  skip: True  # [py<38 or py>38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy  >=1.15.3
    - cython
    - setuptools
    - zlib
  run:
    - python
    - bedtools >=2.23.1
    - cloudpickle >=0.4.0
    - ftputil >=3.3.1,<4.0.0
    - numpy >=1.15.3
    - pandas >=0.23.3
    - scipy >=1.1.0
    - pybedtools >=0.7.8
    - pybigwig >=0.3.12
    - pyyaml >=3.12
    - requests >=2.13.0
    - cffi >=1.10.0
    - pyparsing >=2.2.0
    - biopython >=1.69
    - matplotlib-base >=2.0.2
    - plotnine >=0.4.0
    - mpmath >=1.1.0
    - scikit-learn >=0.21.2
    - python-graphviz
    - seaborn
    - future
    - nose
    - xz
    - bzip2
    - billiard >=3.6.4.0
    - liblapack >=3.9.0

test:
  imports:
    - pygtftk
  commands:
    - gtftk -h

about:
  home: http://github.com/dputhier/pygtftk
  license: MIT
  summary: 'The gtftk suite providing facilities to manipulate genomic annotations in gtf format.'
