{% set version = "1.3" %}

package:
  name: metawrap-mg
  version: "{{ version }}"

source:
  url: https://github.com/bxlab/metaWRAP/archive/v{{ version }}.tar.gz
  md5: 7bc68136196d226155f1848444f31442

build:
  noarch: generic
  number: 0

requirements:
  build: 

  run:
    - biopython =1.68
    - blas =2.5 mkl
    - blast =2.6.0
    - bmtagger =3.101
    - bowtie2 =2.3.5
    - bwa =0.7.17
    - checkm-genome =1.0.12
    - concoct =1.0.0
    - fastqc =0.11.8
    - kraken =1.1
    - kraken2 =2.0
    - krona =2.7
    - matplotlib =2.2.3
    - maxbin2 =2.2.6
    - megahit =1.1.3
    - metabat2 =2.12.1
    - openssl =1.0
    - pandas =0.24.2
    - perl-bioperl
    - pplacer =1.1.alpha19
    - prokka =1
    - quast =5.0.2
    - r-ggplot2 =3.1.0
    - r-reshape2
    - r-recommended =3.5.1
    - salmon =0.13.1
    - samtools =1.9
    - seaborn =0.9.0
    - spades =3.13.0
    - taxator-tk =1.3.3e
    - trim-galore =0.5.0
    # not actually direct dependencies, only here to speed up dependency resolution
#    - r-base >=4
    - gcc_linux-64 >=9.4.0
    - python =2.7.15

test:
  commands:
    - metawrap -h
    - metawrap read_qc -h
    - which config-metawrap

about:
  home: https://github.com/bxlab/metaWRAP
  license: MIT
  summary: "MetaWRAP is a pipeline for genome-resolved metagenomic data analysis"
